### ISSUE TITLE
Make the top bar of a bslib app su-yellow

### ISSUE THREAD

**Issue by matt-dray** [The-Strategy-Unit/su-brand-yml#10]
The current `_brand.yml` has `su-yellow` in it, but it's not clear what key is needed to set the top navbar as yellow.

Changing the `background` value does change the bar, oddly.

Solution likely here: https://github.com/quarto-dev/quarto-cli/discussions/11355

Related: https://github.com/quarto-dev/quarto-cli/issues/11471

**Comment by matt-dray** [comment]
Yeah, I think you can add to `defaults` to affect specific items. So this works for the navbar colour:

```
color:
  palette:
    my-blue: "#0000FF"

defaults:
  shiny:
    theme:
      defaults:
        navbar-bg: $brand-my-blue # i.e. '$brand-<palette key name>'
```
